### ISSUE TITLE
[Errno 13] Permission denied: '/workspace_map.yml'

### ISSUE THREAD

**Issue by wiryawan46** [ektormak/Lyssandra#2]
> `  File "/Volumes/DEV/ular_gigit/Riset2/Lyssandra/lyssa/examples/object_classification/caltech101.py", line 2, in <module>
>     from lyssa.classify import linear_svm
>   File "/Volumes/DEV/ular_gigit/Riset2/Lyssandra/lyssa/__init__.py", line 1, in <module>
>     from .feature_extract import hmp_network
>   File "/Volumes/DEV/ular_gigit/Riset2/Lyssandra/lyssa/feature_extract/__init__.py", line 1, in <module>
>     from .preproc import preproc
>   File "/Volumes/DEV/ular_gigit/Riset2/Lyssandra/lyssa/feature_extract/preproc.py", line 5, in <module>
>     from lyssa.utils.math import normalize, norm_cols
>   File "/Volumes/DEV/ular_gigit/Riset2/Lyssandra/lyssa/utils/__init__.py", line 8, in <module>
>     from .dataset import split_dataset, get_mmap, get_empty_mmap, img_dataset
>   File "/Volumes/DEV/ular_gigit/Riset2/Lyssandra/lyssa/utils/dataset.py", line 8, in <module>
>     from .workspace import mmap_base
>   File "/Volumes/DEV/ular_gigit/Riset2/Lyssandra/lyssa/utils/workspace.py", line 13, in <module>
>     open(workspace_map_file, 'wa').close()
> IOError: [Errno 13] Permission denied: '/workspace_map.yml'`

I always get this error, do you have any idea?

**Comment by ektormak** [comment]
As is mentioned in https://github.com/ektormak/Lyssandra#installation the workspace path is the location of the directory in which feature vectors will be saved. From the output, it seems that you are using a `yml` file instead. Also, make sure you have the right permissions.
